server:
  port: 8082

spring:
  application:
    name: orders-service

  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: postgres
    password: example

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-inbox-group
      auto-offset-reset: earliest
    producer:
      retries: 3

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html