server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: 1354

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-group
    producer:
      retries: 3
  
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html